export const CHATS_LOAD_REQUEST = "CHATS_REQUEST";
export const CHATS_LOAD_SUCCESS = "CHATS_SUCCESS";
export const CHATS_LOAD_FAILURE = "CHATS_FAILURE";
export const CHATS_CREATE_REQUEST = "CHATS_CREATE_REQUEST";
export const CHATS_CREATE_SUCCESS = "CHATS_CREATE_SUCCESS";
export const CHATS_CREATE_FAILURE = "CHATS_CREATE_FAILURE";
